#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define MAX_THREADS 8

#define MAX_CHUNK_SIZE_1 4096

#define MAX_CHUNK_SIZE_2 8192

#define DEFAULT_NUM_THREADS 4

#define DEFAULT_MAX_CHUNK_SIZE 4096

#endif /* CONSTANTS_H_ */
